### 2025.3.29-3.30
### 跟学 [Python深度学习：NumPy数组库](https://www.bilibili.com/video/BV1H84y1g7RE/?share_source=copy_web&vd_source=43c4eb4ed8da935694eaeb473fd0f6cb)

In [2]:
import numpy as np

#### 一、数组的定义

##### 1. 数组元素的类型是整数型或浮点数型的，在初始化时被定义

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
arr[4] = 7.0
print(arr)
arr = arr.astype(float) # 类型转换
print(arr)
arr = arr.astype(int)
print(arr * 1.0) # 数组运算时，若整体乘于浮点数，则会自动转换为浮点数
print(arr / 1) # 除法运算时，若整体除以某个即使不为浮点数的数，都会自动转换为浮点数
# 总结：在运算时，NumPy会自动转换数据类型以避免数据丢失，趋向于整体转换。(全体共同改变定理)

[1 2 3 4 5]
[1 2 3 4 7]
[1. 2. 3. 4. 7.]
[1. 2. 3. 4. 7.]
[1. 2. 3. 4. 7.]


##### 2. 常见的数组类型有一维数组(向量)和多维数组(矩阵)

In [8]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr1,arr1.shape)
print(arr2,arr2.shape)
arr3 = np.array([[1,2,3,4,5,6,7,8,9]])
print(arr3,arr3.shape) # 1行9列的二维数组
print(arr3.reshape(3,-1)) # 变形为3行3列的二维数组,-1表示自动计算列数
print(arr3.reshape(-1)) # 变形为一维数组

[1 2 3] (3,)
[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2 3 4 5 6 7 8 9]] (1, 9)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


#### 二、数组的创建

##### 1. 递增数组

In [13]:
print(np.arange(1,10,2)) # 1到10，步长为2的数组
print(np.arange(0,1,0.1)) # 0到1，步长为0.1的数组
print(np.arange(1,0,-0.1)) # 1到0，步长为-0.1的数组

[1 3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[1.  0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1]


##### 2. 零/单位/对角矩阵

In [16]:
print(np.zeros(10)) # 1到10的零向量
print(np.zeros((2,3))) # 3行4列的二维矩阵
print(np.ones(10)) # 1到10的单位向量
print(np.ones((2,2))) # 2行2列的1矩阵
print(np.eye(3)) # 3行3列的单位矩阵
print(np.eye(3,4)) # 3行4列的单位矩阵，非方阵，非对称矩阵
print(np.diag([1,2,3])) # 1，2，3为对角线元素的对角矩阵
print(np.diag([1,2,3],k=1)) # 1，2，3为上对角线元素的对角矩阵

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


##### 3. 随机矩阵

In [ ]:
print(np.random.random((2,3))) # 2行3列的随机数矩阵，范围在[0,1)
print(90 * np.random.random((2,3)) + 10.0) # 2行3列的随机数矩阵，范围在[10,100)
print(np.random.randint(10,100,(2,3))) # 2行3列的随机数矩阵，范围在[10,100)
print(np.random.randn(2,3)) # 2行3列的随机数矩阵,标准正态分布
print(np.random.normal(70,30,(2,3))) # 2行3列的随机数矩阵,均值为70，标准差为30的正态分布

[[0.98292795 0.72677326 0.95810621]
 [0.80040028 0.34471636 0.98900491]]
[[65.88707545 84.49501883 99.10244328]
 [71.76559589 97.83911202 92.26658336]]
[[60 94 66]
 [63 73 84]]
[[-1.40663863 -2.38175848  0.06100711]
 [ 2.12209589 -0.36360881 -0.33228556]]
[[44.27601158 89.12700521 33.95493986]
 [51.93322562 82.06351164 74.78436717]]


#### 三、数组的索引

##### 1. 访问数组元素，索引从零开始

In [31]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1[0,1]) # 取出第一行第二列的元素
print(arr1[0,-1]) # 取出第一行最后一列的元素(逆向访问)
print(arr1[0]) # 取出第一行的元素
print(arr1[:,0]) # 取出第一列的元素
arr1[0,1] = 10.8 # 修改第一行第二列的元素，截断为整数
print(arr1)

2
3
[1 2 3]
[1 4]
[[ 1 10  3]
 [ 4  5  6]]


##### 2. 花式索引

In [34]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2[[0,1],[1,2]]) # 取出第一行第二列和第二行第三列的元素 
print(np.diag(arr2)) # 取出对角线元素
arr3 = np.ones((3,3)) # 3行3列的1矩阵
arr3[[0,1,2],[2,1,0]] = 0.5 # 对角线元素赋值为0.5
print(arr3)

[2 6]
[1 5]
[[1.  1.  0.5]
 [1.  0.5 1. ]
 [0.5 1.  1. ]]


##### 3. 数组的切片索引 (左开右闭)

In [49]:
arr4 = np.arange(10)
arr5 = arr4.reshape(2,5) # 2行5列的矩阵
print(arr4)
print(arr4[::3]) # 取出从第一个元素开始，每隔4个元素取一个元素
print(arr4[1:-1:3]) # 切除第一个和最后一个元素，从第二个元素开始，每隔4个元素取一个元素
print(arr5)
print(arr5[0:2,0:3]) # 取出前两行前三列的元素
print(arr5[-1,1:3]) # 取出最后一行第二列到第三列的元素
print(arr5[1,1:-1]) # 取出最后一行第二列到倒数第二列的元素
print(arr5[::2,::3]) # 取出从第一行开始，每隔2行取一个元素，从第一列开始，每隔3列取一个元素
print(arr5[0,:],arr5[0]) # 取出第一行的元素,两种方式都可以，不推荐使用arr5[0]
print(arr5[1][2]) # 取出第二列第二行的元素,不推荐使用arr5[1][2]
print(arr5.T) # 转置矩阵

[0 1 2 3 4 5 6 7 8 9]
[0 3 6 9]
[1 4 7]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2]
 [5 6 7]]
[6 7]
[6 7 8]
[[0 3]]
[0 1 2 3 4] [0 1 2 3 4]
7
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


##### 4. 数组的切片是引用

In [ ]:
arr6 = np.array([[1,2,3],[4,5,6]])
print(arr6)
arr7 = arr6[0:2,1:3] # 切片操作，取出第一行第二列到第三列和第二行第二列到第三列的元素
print(arr7)
arr8 = arr6[0:2,1:3].copy() # 复制操作，取出第一行第二列到第三列和第二行第二列到第三列的元素
arr7[0,0] = 10 # 修改第一行第二列的元素
print(arr6) # 修改了原数组的值，切片操作是引用操作
print(arr8) # 没有修改原数组的值，复制操作是值操作


[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[ 1 10  3]
 [ 4  5  6]] [[10  3]
 [ 5  6]] [[2 3]
 [5 6]]


##### 5. 数组幅值也是引用

In [63]:
arr9 = np.array([[1,2,3],[4,5,6]])
arr10 = arr9
arr10[0,0] = 10 # 修改第一行第一列的元素
print(arr9) # 修改了原数组的值，赋值操作是引用操作

[[10  2  3]
 [ 4  5  6]]


#### 四、数组的变形

##### 1. 数组的转置 

In [ ]:
arr1 = np.array([1,2,3,4,5,6]) # 一维数组
print(arr1.T) # 转置操作，仍然是一维数组，没有变化，一维数组(向量)没有转置的概念
print(arr1.reshape(2,-1).T) # 变为二维数组后转置

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]


##### 2. 数组的翻转

In [68]:
arr2 = np.arange(10)
print(arr2) # 0到9的数组
print(np.flipud(arr2)) # 反转数组，翻转上下
print(np.fliplr(arr2.reshape(2,-1))) # 反转数组，翻转左右
arr2

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[[4 3 2 1 0]
 [9 8 7 6 5]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 3. 数组的拼接

In [ ]:
arr3 = np.arange(10).reshape(2,-1) # 0到9的二维数组
print(arr3)
arr4 = np.arange(0,1,0.1).reshape(2,-1) # 0到1的数组
print(arr4)
print(np.concatenate((arr3,arr4),axis=0)) # 纵向拼接，默认拼接
print(np.concatenate((arr3,arr4),axis=1)) # 横向拼接

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0.  0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8 0.9]]
[[0.  1.  2.  3.  4. ]
 [5.  6.  7.  8.  9. ]
 [0.  0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8 0.9]]
[[0.  1.  2.  3.  4.  0.  0.1 0.2 0.3 0.4]
 [5.  6.  7.  8.  9.  0.5 0.6 0.7 0.8 0.9]]


##### 4. 数组的分裂

In [ ]:
arr5 = np.arange(10)
arr6,arr7,arr8 = np.split(arr5,[2,8]) # 将数组分为三部分，arr6为前两位，arr7为中间六位，arr8为最后两位
print(arr6,arr7,arr8)
arr9 = np.arange(10).reshape(2,-1) # 0到9的二维数组
print(arr9)
print(np.split(arr9,[1])) # 按行分割
print(np.split(arr9,[1,3], axis=1)) # 按列分割，分为三部分
print(np.hsplit(arr9,1)) # 按行分割，分为两部分
print(np.vsplit(arr9,2)) # 按列分割，分为两部分

[0 1] [2 3 4 5 6 7] [8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]
[array([[0],
       [5]]), array([[1, 2],
       [6, 7]]), array([[3, 4],
       [8, 9]])]
[array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])]
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]


#### 五、数组的运算

##### 1. 数组的加减乘除

In [ ]:
arr1 = np.arange(6).reshape(2,-1) # 0到5的二维数组
print(arr1)
print(arr1 + 1) # 数组加法
arr2 = np.array([[1,2,3],[4,5,6]]).astype(float) # 2行3列的浮点数矩阵
print(arr1 - arr2) # 数组减法
print(arr1 * arr2) # 数组乘法，对应元素相乘
print(arr1 / arr2) # 数组除法，对应元素相除
print((arr2-3) ** arr1) # 数组乘方，对应元素相幂

[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[-1. -1. -1.]
 [-1. -1. -1.]]
[[ 0.  2.  6.]
 [12. 20. 30.]]
[[0.         0.5        0.66666667]
 [0.75       0.8        0.83333333]]
[[  1.  -1.   0.]
 [  1.  16. 243.]]


##### 2. 广播

In [99]:
arr3 = np.random.randn(2,3) # 2行3列的随机数矩阵,标准正态分布
print(arr3)
arr4 = np.array([2,3,4])
print(arr3 * arr4) # 数组乘法，对应元素相乘，广播机制
arr5 = np.array([[1],[2]])
print(arr3 + arr5) # 数组加法，对应元素相乘，广播机制
print(arr4 - arr5) # 数组减法，对应元素相乘，广播机制

[[-0.24513948  0.37116076  0.55718665]
 [-0.2863277  -1.67126741 -0.22781796]]
[[-0.49027895  1.11348229  2.22874661]
 [-0.57265539 -5.01380223 -0.91127183]]
[[0.75486052 1.37116076 1.55718665]
 [1.7136723  0.32873259 1.77218204]]
[[1 2 3]
 [0 1 2]]


#### 六、数组的函数

##### 1. 矩阵的乘积

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2],[3,4],[5,6]])
print(arr1 @ arr2) # 矩阵乘法，内积
print(np.dot(arr1,arr2)) # 矩阵乘法的另一种写法
arr3 = np.arange(2)
print(arr3 @ arr1) # 向量在矩阵乘法时，向量会被视为行向量

[[22 28]
 [49 64]]
[[22 28]
 [49 64]]
[4 5 6]


##### 2. 数学函数

In [ ]:
arr4 = np.random.randn(2,3) # 2行3列的随机数矩阵,标准正态分布
print('arr4 = ',arr4)
print('所有元素绝对值 = ', np.abs(arr4)) # 所有元素绝对值
theta = np.arange(4) * np.pi / 3 # 0到2π的数组
print('theta = ', theta)
print(np.sin(theta)) # 计算正弦值 # 默认为弧度制
print(np.cos(theta)) # 计算余弦值 # 默认为弧度制
print(np.tan(theta)) # 计算正切值 # 默认为弧度制
x = np.abs(1 + np.random.randn(3)) # 10个随机数
print('x = ',x)
print('e^x = ',np.exp(x)) # 计算e的x次方
print('2^x = ',2**x) # 计算2的x次方
print('lnx = ',np.log(x)) # 计算x的自然对数
print('log10x = ',np.log10(x)) # 计算x的以10为底的对数
print('log10x = ',np.log(x) / np.log(10)) # 计算x的以10为底的对数的另一种写法

arr4 =  [[ 0.02754661 -0.0150148   1.07787788]
 [ 0.06952109  1.0184456  -1.33015054]]
arr4所有元素求和 =  0.8482258494606334
所有元素绝对值 =  [[0.02754661 0.0150148  1.07787788]
 [0.06952109 1.0184456  1.33015054]]
theta =  [0.         1.04719755 2.0943951  3.14159265]
[0.00000000e+00 8.66025404e-01 8.66025404e-01 1.22464680e-16]
[ 1.   0.5 -0.5 -1. ]
[ 0.00000000e+00  1.73205081e+00 -1.73205081e+00 -1.22464680e-16]
x =  [2.49907819 0.95588842 1.80484478]
e^x =  [12.17126923  2.60098033  6.07902782]
2^x =  [5.65324097 1.9397738  3.49391566]
lnx =  [ 0.91592194 -0.04511408  0.5904746 ]
log10x =  [ 0.39777984 -0.0195928   0.25643986]
log10x =  [ 0.39777984 -0.0195928   0.25643986]


##### 3. 聚合函数

In [126]:
arr5 = np.random.random((2,3)) # 2行3列的随机数矩阵,标准正态分布
print(arr5)
print('按维度一求最大值: ',np.max(arr5,axis=0)) # 按列求最大值
print('按维度二求最大值: ',np.max(arr5,axis=1)) # 按行求最大值
print('整体求最大值: ',np.max(arr5)) # 整体求最大值
print('所有元素求和 = ',np.sum(arr5)) # 所有元素求和
arr6 = np.array([[1,2,3],[4,5,6]])
print(arr6)
print('按维度一求和: ',np.sum(arr6,axis=0)) # 按列求和
print('按维度二求和: ',np.sum(arr6,axis=1)) # 按行求和
print('按维度一求均值: ',np.mean(arr6,axis=0)) # 按列求均值
print('按维度二求均值: ',np.mean(arr6,axis=1)) # 按行求均值
print('整体求均值: ',np.mean(arr6)) # 整体求均值
print('按维度一求标准差: ',np.std(arr6,axis=0)) # 按列求标准差
print('按维度二求标准差: ',np.std(arr6,axis=1)) # 按行求标准差
print('整体求标准差: ',np.std(arr6)) # 整体求标准差

[[0.34826552 0.21632584 0.58288027]
 [0.72944024 0.90186539 0.91166502]]
按维度一求最大值:  [0.72944024 0.90186539 0.91166502]
按维度二求最大值:  [0.58288027 0.91166502]
整体求最大值:  0.9116650160907557
所有元素求和 =  3.6904422773549537
[[1 2 3]
 [4 5 6]]
按维度一求和:  [5 7 9]
按维度二求和:  [ 6 15]
按维度一求均值:  [2.5 3.5 4.5]
按维度二求均值:  [2. 5.]
整体求均值:  3.5
按维度一求标准差:  [1.5 1.5 1.5]
按维度二求标准差:  [0.81649658 0.81649658]
整体求标准差:  1.707825127659933


#### 七、布尔型数组

##### 1. 创建布尔型数组

In [129]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1 > 1)
arr2 = (arr1 > 1) & (arr1 < 5) # 逻辑与
print(arr2)
 

[[False  True  True]
 [ True  True  True]]
[[False  True  True]
 [ True False False]]


##### 2. 布尔型数组True的数量

In [ ]:
arr3 = np.random.normal(0,1,1000)
print(np.sum(np.abs(arr3) < 1))# 统计绝对值小于1的元素
print(np.any(arr3 > 3))# 判断是否有元素大于100
arr4 = np.array([[1,2,3],[4,5,6]])
arr5 = np.array([[1,2,3],[4,5,6]]) + np.arange(6).reshape(2,-1) # 2行3列的随机数矩阵,标准正态分布
print(arr5)
print(np.any(arr4 == arr5))# 判断是否有元素相等
arr6 = np.random.normal(500,70,1000)
print(np.all(arr6 > 250)) # 判断是否所有元素都大于250

695
True
[[ 1  3  5]
 [ 7  9 11]]
True
False


##### 3. 布尔型数组作为掩码（索引）

In [258]:
arr7 = np.arange(1,13).reshape(3,4) # 3行4列
print(arr7)
print(arr7[arr7 > 5]) # 取出大于5的元素
arr8 = np.arange(10)
arr9 = np.flipud(arr8) # 反转数组，翻转上下
print(arr8 > arr9)
print(arr8[arr8 > arr9]) # 取出大于翻转后的元素
print(arr8[arr8 == np.max(arr8)]) # 取出最大值的元素
arr9 = np.random.normal(500,70,1000)
print(np.where(arr9 > 650)) # 返回大于500的元素的索引
print(np.where(arr9 == np.max(arr9))) # 返回最大值的元素的索引

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 6  7  8  9 10 11 12]
[False False False False False  True  True  True  True  True]
[5 6 7 8 9]
[9]
(array([ 43,  71, 155, 198, 200, 329, 416, 529, 689, 696, 732, 735, 767,
       774, 799, 801, 867], dtype=int64),)
(array([529], dtype=int64),)
