# pytorch环境测试

In [1]:
import torch
print(torch.cuda.is_available())  # 检查 CUDA 是否可用
print(torch.cuda.get_device_name(0))  # 查看 CUDA 设备名称

True
NVIDIA GeForce GTX 1660 Ti


# gym包测试

In [11]:
import gym

env = gym.make('CartPole-v1')

state = env.reset()

for t in range(100):
    env.render()
    print(state)
    
    action = env.action_space.sample()
    state, reward, done, info, _ = env.step(action)
    
    if done: 
        print("Finished")
        break
    
env.close()

(array([ 0.01892864, -0.01862025,  0.00660771, -0.00964111], dtype=float32), {})
[ 0.01855623  0.17640632  0.00641488 -0.30023193]
[ 0.02208436 -0.01880648  0.00041024 -0.0055328 ]
[ 0.02170823  0.17630959  0.00029959 -0.29808626]
[ 0.02523442 -0.01881663 -0.00566214 -0.00530886]
[ 0.02485809 -0.21385692 -0.00576831  0.2855822 ]
[ 2.0580947e-02 -4.0889615e-01 -5.6668996e-05  5.7644027e-01]
[ 0.01240303 -0.6040173   0.01147214  0.8691054 ]
[ 3.2267967e-04 -7.9929340e-01  2.8854245e-02  1.1653731e+00]
[-0.01566319 -0.9947788   0.0521617   1.466961  ]
[-0.03555876 -0.8003328   0.08150093  1.1910173 ]
[-0.05156542 -0.6063559   0.10532127  0.92495257]
[-0.06369254 -0.8027307   0.12382033  1.2487897 ]
[-0.07974716 -0.60939425  0.14879611  0.9973156 ]
[-0.09193504 -0.80615854  0.16874243  1.3327855 ]
[-0.10805821 -1.0029576   0.19539814  1.6731665 ]
Finished
